version: 2
updates:
  - package-ecosystem: 'github-actions'
    directories:
      - '/'
      - '/actions/pygtkwin-env'
    cooldown:
      default-days: 7
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'pip'
    directory: '/'
    cooldown:
      default-days: 7
    schedule:
      interval: 'monthly'
    groups:
      pip:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
