#!/usr/bin/env bash
# Generate and install platform-specific typelibs (GLibWin32-2.0, GioWin32-2.0)
# that glib 2.88.0's girepository auto-loads at runtime.
#
# Without these typelibs, every PyGObject application emits:
#   GLib-GIRepository-CRITICAL **: Unable to load platform-specific GIO
#   introspection data: Typelib file for namespace 'GLibWin32' not found
#
# The vcpkg glib port builds with -Dintrospection=disabled, so these are
# never generated by glib itself.  We compile vendored GIR files with
# g-ir-compiler (already installed by the gobject-introspection port).
#
# We also post-process GLib-2.0.gir and Gio-2.0.gir to remove duplicate
# symbols from the platform-specific GIRs.  Without this, PyGObject 3.56.3
# emits "Name conflict for platform-specific symbol" warnings (pygobject
# bug #760).
#
# Usage: ./generate-platform-typelibs.sh <vcpkg_installed_triplet_dir>
# Example: ./generate-platform-typelibs.sh vcpkg_installed/x86-windows
set -euo pipefail

dir="${1:?usage: $0 <triplet_dir>}"
script_dir="$(cd "$(dirname "$0")" && pwd)"

gir_dir="$dir/share/gir-1.0"
typelib_dir="$dir/lib/girepository-1.0"
gi_tools_dir="$dir/tools/gobject-introspection"
g_ir_compiler="$gi_tools_dir/g-ir-compiler.exe"

if [ ! -f "$g_ir_compiler" ]; then
    echo "ERROR: g-ir-compiler not found at $g_ir_compiler" >&2
    exit 1
fi

if [ ! -d "$gir_dir" ]; then
    echo "ERROR: GIR directory not found: $gir_dir" >&2
    exit 1
fi

if [ ! -d "$typelib_dir" ]; then
    echo "ERROR: typelib directory not found: $typelib_dir" >&2
    exit 1
fi

echo "=== Generating platform-specific typelibs ==="

# Find a usable python (python3 on Linux/macOS, python on Windows Git Bash).
# Honors PYTHON env var for when neither is on PATH (e.g. local Windows builds).
python_bin="${PYTHON:-$(command -v python3 || command -v python || true)}"

# The pygtkwin-env GitHub Action sets PYTHON to a Windows-style path with
# backslashes (e.g. D:\a\...\python.exe) because the cmd/pwsh steps need it
# in that form.  bash cannot execute such a path directly (the backslashes
# are treated as literal characters, not separators), so convert it to a
# Unix path via cygpath.  cygpath only exists under Git Bash / MSYS; on
# Linux/macOS PYTHON is already a Unix path and cygpath is absent, so the
# conversion is skipped there.
if [ -n "$python_bin" ] && command -v cygpath >/dev/null 2>&1 \
    && [[ "$python_bin" == *\\* || "$python_bin" == ?:* ]]; then
    python_bin="$(cygpath -u "$python_bin")"
fi

if [ -z "$python_bin" ]; then
    echo "ERROR: neither python3 nor python found on PATH (set PYTHON env var)" >&2
    exit 1
fi

# 1. Install the platform GIRs before compiling their typelibs.
cp "$script_dir/gir/GLibWin32-2.0.gir" "$script_dir/gir/GioWin32-2.0.gir" "$gir_dir/"

# 2. Remove only symbols provided by the matching platform GIR, then
#    recompile the base typelibs from the filtered metadata.
for namespace in GLib Gio; do
    "$python_bin" "$script_dir/gir/filter_glib_gir.py" \
        "$gir_dir/$namespace-2.0.gir" "$gir_dir/${namespace}Win32-2.0.gir" \
        "$gir_dir/$namespace-2.0.gir.filtered"
    mv "$gir_dir/$namespace-2.0.gir.filtered" "$gir_dir/$namespace-2.0.gir"
    "$g_ir_compiler" \
        --includedir="$gir_dir" \
        --output="$typelib_dir/$namespace-2.0.typelib" \
        "$gir_dir/$namespace-2.0.gir"
    echo "OK: Recompiled $namespace-2.0.typelib (platform duplicates removed)"
done

# 3. Compile the generated-platform API typelibs.
for namespace in GLibWin32 GioWin32; do
    "$g_ir_compiler" \
        --includedir="$gir_dir" \
        --output="$typelib_dir/$namespace-2.0.typelib" \
        "$gir_dir/$namespace-2.0.gir"
    echo "OK: Installed $namespace-2.0.typelib + $namespace-2.0.gir"
done

echo "=== Platform-specific typelibs generated successfully ==="
